# Generated by Django 5.2.16 on 2026-07-17 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('category', models.CharField(blank=True, help_text='Необязательная группировка, например «Маркетинг».', max_length=100, verbose_name='Категория')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(help_text='Понятное имя аккаунта для панели, например «Аккаунт №1».', max_length=120, verbose_name='Название')),
                ('phone', models.CharField(blank=True, help_text='В международном формате, например +79991234567.', max_length=32, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('new', 'Новый (не авторизован)'), ('code_sent', 'Ожидает код подтверждения'), ('active', 'Активен'), ('disabled', 'Отключён'), ('error', 'Ошибка')], default='new', max_length=16, verbose_name='Статус')),
                ('is_enabled', models.BooleanField(default=True, help_text='Если выключено — аккаунт не подключается и не отвечает.', verbose_name='Использовать в работе')),
                ('session_string', models.TextField(blank=True, editable=False, verbose_name='Строка сессии')),
                ('telegram_user_id', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Username')),
                ('display_name', models.CharField(blank=True, editable=False, max_length=200, verbose_name='Имя в Telegram')),
                ('auth_session', models.TextField(blank=True, editable=False)),
                ('auth_phone_code_hash', models.CharField(blank=True, editable=False, max_length=128)),
                ('last_error', models.TextField(blank=True, editable=False, verbose_name='Последняя ошибка')),
            ],
            options={
                'verbose_name': 'Telegram-аккаунт',
                'verbose_name_plural': 'Telegram-аккаунты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=200, verbose_name='Название группы')),
                ('chat_id', models.BigIntegerField(blank=True, help_text='Числовой идентификатор чата. Заполнится сам, если указан @username или ссылка.', null=True, verbose_name='ID чата')),
                ('chat_username', models.CharField(blank=True, help_text='Для публичных групп, без символа @ (например: my_group).', max_length=64, verbose_name='@username чата')),
                ('invite_link', models.CharField(blank=True, help_text='Ссылка вида https://t.me/+... для приватных групп.', max_length=255, verbose_name='Ссылка-приглашение')),
                ('trigger_scope', models.CharField(choices=[('host', 'Только сообщения ведущего'), ('anyone', 'Сообщения любого участника')], default='host', max_length=16, verbose_name='Реагировать на сообщения')),
                ('host_username', models.CharField(blank=True, help_text='Чьи сообщения запускают сценарии (без @). Если пусто — определяется по ID.', max_length=64, verbose_name='Username ведущего')),
                ('host_user_id', models.BigIntegerField(blank=True, help_text='Можно указать вместо username для точного совпадения.', null=True, verbose_name='Telegram ID ведущего')),
                ('is_active', models.BooleanField(default=True, help_text='Если выключено — сценарии этой группы не срабатывают.', verbose_name='Группа активна')),
                ('owner', models.ForeignKey(blank=True, help_text='Пользователь панели, который управляет этой группой.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=200, verbose_name='Название сценария')),
                ('match_type', models.CharField(choices=[('contains', 'Содержит текст'), ('equals', 'Точно совпадает'), ('starts', 'Начинается с'), ('regex', 'Регулярное выражение'), ('any', 'Любое сообщение')], default='contains', max_length=16, verbose_name='Тип условия')),
                ('trigger_text', models.CharField(blank=True, help_text='На какое сообщение реагировать. Для «Любое сообщение» можно оставить пустым.', max_length=500, verbose_name='Текст-триггер')),
                ('case_sensitive', models.BooleanField(default=False, verbose_name='Учитывать регистр')),
                ('is_enabled', models.BooleanField(default=True, help_text='Быстрое включение/отключение без удаления.', verbose_name='Сценарий включён')),
                ('cooldown_seconds', models.PositiveIntegerField(default=0, help_text='Минимум секунд между повторными срабатываниями одного сценария (0 — без ограничения).', verbose_name='Пауза перед повтором, сек')),
                ('priority', models.IntegerField(default=0, help_text='Чем больше число, тем раньше проверяется сценарий.', verbose_name='Приоритет')),
                ('last_triggered_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последнее срабатывание')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='simulator.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('delay_seconds', models.PositiveIntegerField(default=15, help_text='Через сколько секунд после сообщения-триггера отправить эту реплику.', verbose_name='Задержка, сек')),
                ('text', models.TextField(blank=True, help_text='Если выбран шаблон и поле пустое — будет отправлен текст шаблона.', verbose_name='Текст реплики')),
                ('reply_to_trigger', models.BooleanField(default=False, help_text='Отправить как ответ (reply) на сообщение ведущего.', verbose_name='Ответить на сообщение-триггер')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Реплика включена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='simulator.scenario', verbose_name='Сценарий')),
                ('template', models.ForeignKey(blank=True, help_text='Можно взять готовый текст из библиотеки.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='simulator.messagetemplate', verbose_name='Шаблон')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='simulator.telegramaccount', verbose_name='Отвечающий аккаунт')),
            ],
            options={
                'verbose_name': 'Реплика сценария',
                'verbose_name_plural': 'Реплики сценария',
                'ordering': ['order', 'delay_seconds', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен в группе')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.group', verbose_name='Группа')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.telegramaccount', verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Аккаунт в группе',
                'verbose_name_plural': 'Аккаунты в группе',
                'unique_together': {('group', 'account')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='groups', through='simulator.GroupMembership', to='simulator.telegramaccount', verbose_name='Аккаунты группы'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('trigger_text', models.TextField(blank=True, verbose_name='Сообщение-триггер')),
                ('trigger_sender', models.CharField(blank=True, max_length=200, verbose_name='Автор триггера')),
                ('sent_text', models.TextField(blank=True, verbose_name='Отправленный текст')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='scheduled', max_length=16, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в')),
                ('error', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='simulator.group', verbose_name='Группа')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='simulator.scenario', verbose_name='Сценарий')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='simulator.scenarioreply', verbose_name='Реплика')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='simulator.telegramaccount', verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал работы',
                'ordering': ['-created_at'],
            },
        ),
    ]
