# Generated by Django 5.2.16 on 2026-07-18 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioreply',
            name='number_max',
            field=models.IntegerField(blank=True, help_text='Верхняя граница случайного числа для {number}.', null=True, verbose_name='Число: до'),
        ),
        migrations.AddField(
            model_name='scenarioreply',
            name='number_min',
            field=models.IntegerField(blank=True, help_text='Нижняя граница случайного числа для {number}. Оставьте пустым, если {number} не используете.', null=True, verbose_name='Число: от'),
        ),
        migrations.AddField(
            model_name='scenarioreply',
            name='number_thousands',
            field=models.BooleanField(default=False, help_text='Показывать число как «1 250 000» вместо «1250000».', verbose_name='Разделять тысячи пробелами'),
        ),
        migrations.AlterField(
            model_name='scenarioreply',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы временно отключить эту реплику, не удаляя её.', verbose_name='Реплика включена'),
        ),
        migrations.AlterField(
            model_name='scenarioreply',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок показа в списке (на отправку не влияет — там важна задержка).', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='scenarioreply',
            name='reply_to_trigger',
            field=models.BooleanField(default=False, help_text='Если включено — реплика будет оформлена как ответ (со стрелочкой) на сообщение-триггер. Если выключено — просто новое сообщение в чат.', verbose_name='Ответить именно на сообщение ведущего'),
        ),
        migrations.AlterField(
            model_name='scenarioreply',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Можно подставить текст из библиотеки шаблонов вместо ручного ввода. Если поле «Текст реплики» заполнено — используется оно, а не шаблон.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='simulator.messagetemplate', verbose_name='Готовый шаблон (необязательно)'),
        ),
        migrations.AlterField(
            model_name='scenarioreply',
            name='text',
            field=models.TextField(blank=True, help_text='Что именно напишет аккаунт. Можно вставить {number} — вместо него подставится случайное число из диапазона ниже. Пример: «Босс, мы получили {number}$ дохода».', verbose_name='Текст реплики'),
        ),
    ]
