# Generated by Django 5.2.16 on 2026-07-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_scenarioreply_number_max_scenarioreply_number_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Бот включён')),
                ('heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Последний отклик процесса')),
            ],
            options={
                'verbose_name': 'Состояние бота',
                'verbose_name_plural': 'Состояние бота',
            },
        ),
        migrations.AlterField(
            model_name='scenarioreply',
            name='text',
            field=models.TextField(blank=True, help_text='Что именно напишет аккаунт. Можно подставлять случайные числа: напишите диапазон прямо в тексте в фигурных скобках — {от-до}. Пример: «Босс, мы получили {50000-200000}$ за {5-30} дней». Таких диапазонов может быть сколько угодно, у каждого своё число.', verbose_name='Текст реплики'),
        ),
    ]
