# Generated by Django 5.2.16 on 2026-07-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_botstate_alter_scenarioreply_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('kind', models.CharField(choices=[('private', 'Личные сообщения'), ('group', 'Группа')], default='private', max_length=10, verbose_name='Тип')),
                ('peer_id', models.BigIntegerField(help_text='Внутренний идентификатор чата в Telegram.', verbose_name='ID чата/собеседника')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Кто/что')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Username')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение')),
                ('last_text', models.TextField(blank=True, verbose_name='Текст последнего сообщения')),
                ('last_outgoing', models.BooleanField(default=False, verbose_name='Последнее — наше')),
                ('unread', models.PositiveIntegerField(default=0, verbose_name='Непрочитано')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='simulator.telegramaccount', verbose_name='Наш аккаунт')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogs', to='simulator.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DialogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID сообщения в Telegram')),
                ('outgoing', models.BooleanField(default=False, verbose_name='Исходящее (от нас)')),
                ('via_panel', models.BooleanField(default=False, verbose_name='Отправлено из панели')),
                ('sender_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID автора')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='Автор')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Время сообщения')),
                ('status', models.CharField(choices=[('pending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='sent', max_length=10, verbose_name='Статус отправки')),
                ('error', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialog_messages', to='simulator.telegramaccount', verbose_name='Аккаунт-отправитель')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='simulator.dialog', verbose_name='Диалог')),
            ],
            options={
                'verbose_name': 'Сообщение диалога',
                'verbose_name_plural': 'Сообщения диалогов',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dialog',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'group')), fields=('peer_id',), name='uniq_group_dialog'),
        ),
        migrations.AddConstraint(
            model_name='dialog',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'private')), fields=('account', 'peer_id'), name='uniq_private_dialog'),
        ),
        migrations.AddConstraint(
            model_name='dialogmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('tg_id__isnull', False)), fields=('dialog', 'tg_id'), name='uniq_dialog_message'),
        ),
    ]
