# Generated by Django 5.2.16 on 2026-07-18 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_dialog_dialogmessage_dialog_uniq_group_dialog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(help_text='Понятное имя приложения, например «Приложение №1».', max_length=120, verbose_name='Название')),
                ('api_id', models.BigIntegerField(help_text='Из https://my.telegram.org → API development tools.', verbose_name='API ID')),
                ('api_hash', models.CharField(help_text='Из https://my.telegram.org (там же, где API ID).', max_length=64, verbose_name='API Hash')),
                ('is_default', models.BooleanField(default=False, help_text='Это приложение возьмут аккаунты, которым приложение не выбрано явно. Отметить можно только одно.', verbose_name='Использовать по умолчанию')),
            ],
            options={
                'verbose_name': 'Главный аккаунт (API Telegram)',
                'verbose_name_plural': 'Главные аккаунты (API Telegram)',
                'ordering': ['-is_default', 'title'],
            },
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='api_credentials',
            field=models.ForeignKey(blank=True, help_text='Через какое API-приложение работает этот аккаунт. Распределяйте аккаунты по разным приложениям, чтобы снизить риск блокировок. Пусто — приложение по умолчанию или значения из .env. Выбирайте ДО подключения: смена приложения у уже подключённого аккаунта требует повторной авторизации.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='simulator.apicredentials', verbose_name='Главный аккаунт (приложение)'),
        ),
    ]
